name: Lab on Env Var
on:
  push:
    branches:
      - main
env:
  JAVA_VERSION: 17
jobs:
  Build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name : Checking out
        run: echo "Checkout"
        run: echo "setting up java version to $JAVA_VERSION" 
  Deployment:
    name: Deploy Job
    runs-on: ubuntu-latest
    env:
      APP_NAME: "Docker"
    steps:
      - name : Checking out
        run: echo "Checkout"
      - name: Building docker app
        run: echo "Building Docker application"
      - name: Building docker app
        run: echo "hello $APP_NAME"
