name: Lab on Env Var
on:
  workflow_dispacth:
env:
  JAVA_VERSION: 17
jobs:
  Build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      run: echo "Checkout"
      run: echo "setting up java version to $JAVA_VERSION"

  
  Deployment:
    name: Deploy Job
    runs-on: ubuntu-latest
    steps:
      run: echo "Checkout"
      run: echo "Building Docker application"
